;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        kill-region
        kmacro-insert-counter
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        end-of-buffer
        indent-for-tab-command
        ))
